# ---
# apiVersion: argoproj.io/v1alpha1
# kind: AppProject
# metadata:
#   name: keycloak-helm
# spec:
#   description: Management keycloak of Argo CD
#   # some of my apps within argocd project need to create cluster resources
#   clusterResourceWhitelist:
#   - group: '*'
#     kind: '*'
#   destinations:
#   - namespace: keycloak
#     server: https://kubernetes.default.svc
#   sourceRepos:
#   - https://charts.bitnami.com/bitnami
#   #
#   # lots of other repos here
#   #
#   #- https://github.com/helm/charts.git
# ---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-helm
  namespace: argocd
spec:
  destination:
    namespace: keycloak
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  source:
    path: keycloak
    repoURL: https://github.com/robsonsantosdevops/charts
    #https://charts.bitnami.com/bitnami

    targetRevision: 14.0.0
    helm:
      valueFiles:
      - values.yaml
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: test-infra
# spec:
#   destination:
#     namespace: argocd
#     server: https://kubernetes.default.svc
#   project: keycloak-helm
#   syncPolicy:
#     automated:
#       prune: true
#   source:
#     path: argocd-example-infra
#     repoURL: https://github.com/stevesea/argocd-helm-app-of-apps-example.git
#     targetRevision: test
#     helm:
#       valueFiles:
#       - test-values.yaml