apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
 #   kubernetes.io/createdby: aws-ebs-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/aws-ebs
 # creationTimestamp: "2022-04-21T00:02:43Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    topology.kubernetes.io/region: us-west-2
    topology.kubernetes.io/zone: us-west-2a
  #name: pvc-9221f98f-146a-43d4-8db2-88a7eb3cebc7
  #resourceVersion: "9453119"
  #uid: de58fbfe-a7b0-43e1-ad14-d9aff0f67e58
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: aws://us-west-2a/vol-0aa322c4ae883d376
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-keycloak-postgresql-0
    namespace: keycloak
  #  resourceVersion: "9453064"
  #  uid: 9221f98f-146a-43d4-8db2-88a7eb3cebc7
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - us-west-2a
        - key: topology.kubernetes.io/region
          operator: In
          values:
          - us-west-2
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp2
  volumeMode: Filesystem
status:
  phase: Bound
